# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Bilbo/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/Frodo/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/Galadriel/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/Gandalf/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/Mordor/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/Sauron/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"