qodana:
   only:
      - 1.0.0-alpha
      - merge_requests
   image:
      name: jetbrains/qodana-<linter>
      entrypoint: [""]
   variables:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      QODANA_REMOTE_URL: git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
      QODANA_BRANCH: $CI_COMMIT_BRANCH
      QODANA_REVISION: $CI_COMMIT_SHA
      QODANA_JOB_URL: $CI_JOB_URL
   script:
      - qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana
         --report-dir=$CI_PROJECT_DIR/.github/qodana/report
   artifacts:
      paths:
         - .github/qodana/report/
      expose_as: 'Qodana report'
